### ISSUE TITLE
ESP32 with VSPI not default SPI

### ISSUE THREAD

**Issue by wbadry** [sparkfun/SparkFun_BMI270_Arduino_Library#5]
Hello,
The SPI is used at my end with an SD card. Is there any way to modify it so it uses the ESP32 VSPI class instead of the default SPI? If `SPI.begin()` is used even with modified pins, both will be on the HSPI. I would appreciate the assistance. Thanks

**Comment by sfe-SparkFro** [comment]
Hi there, apologies for the long delay in response!

I've implemented a fix in this branch: https://github.com/sparkfun/SparkFun_BMI270_Arduino_Library/tree/allow_any_spi_port

I've not tested it other than verifying it compiles. Are you able to test if it works on your end? Should be able to run Example 2, and just modify it to use VSPI: `imu.beginSPI(chipSelectPin, clockFrequency, VSPI)`

If it works, we can merge this and make a new release. Hope this helps!

**Comment by sfe-SparkFro** [comment]
I finally got around to testing this, and it seems to work fine. Will get this merged and cut a new release shortly!

Also, correction on my previous code modification- with ESP32, you need to do the following to use VSPI:

```
SPIClass mySpiBus(VSPI);
mySpiBus.begin();
imu.beginSPI(chipSelectPin, clockFrequency, mySpiBus);
```
